var i18n_AccountPreview;
var i18n_TouchID;
var i18n_devRegistration;
var i18n_LoginSettings;
var i18n_GeneralSettings;
var i18n_ProfilenAlerts;
var i18n_MyProfile;
var i18n_Alerts;
var i18n_ForTransfers;
var i18n_ForDeposits;
var i18n_ForPayments;
var i18n_Hi;
var i18n_lastSignin;
var i18n_touchIdHeader;
var i18n_onLabel;
var i18n_offLabel;
var i18n_differentUsername;
var i18n_validUsernamealert;
var i18n_emptyPasswordalert;
var i18n_PasswordMismatchalert;
var i18n_Passwordsuniquealert;
var i18n_validPasswordalert;
var i18n_EmailorPhoneemptyalert;
var i18n_validEmailalert;
var i18n_validSecondaryEmailalert;
var i18n_imagenotSelected;
var i18n_mediaGalleryerror;
var i18n_devRegSuccess;
var i18n_editProfileHeader;
var i18n_editPasswordHeader;
var i18n_editUnameHeader;
var i18n_draftMessages;
var i18n_sentMessages;
var i18n_deletedMessages;
var i18n_myMessages;
var i18n_noDescription;
var i18n_noSubject;
var i18n_sentOn;
var i18n_ReceivedOn;
var i18n_deletedOn;
var i18n_selectSubcategory;
var i18n_createdOn;
var i18n_referenceId;
var i18n_processingTransaction;
var i18n_successtext;
var i18n_termsnConditions;
var i18n_validAmountalert;
var i18n_uploadImagesalert;
var i18n_selectStateAlert;
var i18n_primaryFieldsAlert;
var i18n_validSSNalert;
var i18n_answerSecretQuestns;
var i18n_viewApplicationForm;
var i18n_availableBalance;
var i18n_oneTIme;
var i18n_daily;
var i18n_weeklyOnce;
var i18n_every2Weeks;
var i18n_monthlyOnce;
var i18n_cancelBillPay;
var i18n_savingsAccount;
var i18n_billPaymentTo;
var i18n_repeatBillPay;
var i18n_P2PTransferTo;
var i18n_repeatTransfer;
var i18n_transferTo;
var i18n_recentTransactions;
var i18n_transactionDate;
var i18n_scheduledTransactions;
var i18n_next;
var i18n_times;
var i18n_to;
var i18n_ok;
var i18n_TRANSFER;
var i18n_repeatP2P;
var i18_payAPerson;
var i18n_pay;
var i18n_payBill;
var i18n_scheduledForC;
var i18n_transactionDateC;
var i18n_currentBalance;
var i18n_cancel;
var i18n_Disable;
var i18n_turnOffRememberMe;
var i18n_disableTouchId;
var i18n_UpgradeofApp;
var i18n_Upgrade;
var i18n_UpgradeApp;
var i18n_UpgradeAppAlert;
var i18n_enrollSuccessAlert;
var i18n_appLaunchError;
var i18n_deviceConnectionError;
var i18n_retake;
var i18n_takePhoto;
var i18n_sameAccountAlert;
var i18n_validAmountAlert;
var i18n_unsufficientAmountAlert;
var i18n_selectToAccountAlert;
var i18n_selectFromAccountAlert;
var i18n_selectTonFromAccountAlert;
var i18n_cancelTransferAlert;
var i18n_cancelAlert;
var i18n_btnInfo;
var i18n_YES;
var i18n_NO;
var i18n_default;
var i18n_Once;
var i18n_Weekly;
var i18n_BiWeekly;
var i18n_Monthly;
var i18n_transactionUpdateAlert;
var i18n_selectCountryAlert;
var i18n_enterBeneficiaryNameAlert;
var i18n_enterAccountNumberAlert;
var i18n_enterswiftCodeAlert;
var i18n_enterRoutingNumberAlert;
var i18n_currentBalance;
var i18n_outStandingBalance;
var i18n_cancel;
var i18n_notes;
var i18n_scheduledFor;
var i18n_cancelTransferAlert;
var i18n_ScheduledBillDetails;
var i18n_CompletedBillDetails;
var i18n_fieldsMandatory;
var i18n_AccountMismatchAlert;
var i18n_editP2PPerson;
var i18n_editTransfer;
var i18n_noContacts;
var i18n_enterZipCode;
var i18n_billPayEdit;
var i18n_PendingTransaction;
var i18n_PendingTransactionText;
var i18n_TransferScheduled;
var i18n_depositPending;
var i18n_companyNameAlert;
var i18n_reenterAccountNumberAlert;
var i18n_enterLocation;
var i18n_pickaproduct;
var i18n_msgReply;
var i18n_msgDelete;
var i18n_Card;
var i18n_CardHolder;
var i18n_CardValidThru;
var i18n_cardNumberX;
var i18n_requestPinChange;
var i18n_Cancelling;
var i18n_StolenorLost;
var i18n_Replacing;
var i18n_Deactivating;
var i18n_Activating;
var i18n_CardTypeC;
var i18n_DeactivateCard;
var i18n_ActivateCard;
var i18n_DeactivateCardInfo;
var i18n_cancelCardInfo;
var i18n_ReportCardInfo;
var i18n_ReplacementCardInfo;
var i18n_Confirmationalert;
var i18n_Call;
var i18n_InstructCardsLost;
var i18n_InstructPinChange;
var i18n_cardDeactivated;
var i18n_cardactivated;
var i18n_cardCancelled;
var i18n_replacementReq;
var i18n_openaccountId;
var i18n_contactMsg;
var i18n_workingDays;
var i18n_alertInvalidCred;
var i18n_alertAuthCancelUser;
var i18n_alertAuthCancelBackBtn;
var i18n_alertAuthCancelSystem;
var i18n_alertPasscodeNotSet;
var i18n_alertTouchIdUnavailable;
var i18n_alertTouchIdNotEnrolled;
var i18n_alertTouchIdAuthFailed;
var i18n_accountPreviewAlert;
var i18n_lastMonth;
var i18n_thisMonth;
var i18n_cashFlow;
var i18n_nativeTouchId;
var i18n_unfilledData;
var i18n_Error;
var i18n_DistanceUnknown;
var i18n_turnOnLocationAlert;
var i18n_settings
var i18n_noatmorBranchesFound;
var i18n_Call;
var i18n_noDirections;
var i18n_defaultDirectionListVA;
var i18n_transactionFailed;
var i18n_FailedMsg;
var i18n_select;
var i18n_confirmSignOut;
var i18n_signOut;
var i18n_signOutAlert;
var i18n_Yeslbl;
var i18n_Nolbl
var i18n_depositCancel;
var i18n_cancelDepositAlert;
var i18n_depositSuccessMsg;

function generatei18nKeys()
{
	i18n_AccountPreview = kony.i18n.getLocalizedString("i18n.common.accountPreview");
    i18n_TouchID = kony.i18n.getLocalizedString("i18n.common.touchID");
    i18n_devRegistration =kony.i18n.getLocalizedString("i18n.login.deviceRegisteration");
    i18n_LoginSettings = kony.i18n.getLocalizedString("i18n.settings.loginSettingsC");
    i18n_GeneralSettings = kony.i18n.getLocalizedString("i18n.settings.generalSettingsC");
    i18n_ProfilenAlerts =  kony.i18n.getLocalizedString("i18n.settings.profileAndAlertsC");
    i18n_MyProfile = kony.i18n.getLocalizedString("i18n.settings.myProfile");
    i18n_Alerts = kony.i18n.getLocalizedString("i18n.settings.alerts");
    i18n_ForTransfers = kony.i18n.getLocalizedString("i18n.settings.forTransfers");
    i18n_ForDeposits = kony.i18n.getLocalizedString("i18n.settings.forDeposits");
    i18n_ForPayments = kony.i18n.getLocalizedString("i18n.settings.forPayments");
    i18n_Hi= kony.i18n.getLocalizedString("i18n.common.hic");
    i18n_lastSignin = kony.i18n.getLocalizedString("i18n.common.youLastSignedOnAt");
    i18n_touchIdHeader=kony.i18n.getLocalizedString("i18n.touchId.headingwithoutBank");
    i18n_onLabel= kony.i18n.getLocalizedString("i18n.settings.on");
    i18n_offLabel = kony.i18n.getLocalizedString("i18n.settings.off");
    i18n_differentUsername = kony.i18n.getLocalizedString("i18n.errorMsgs.differentUsername");
    i18n_validUsernamealert = kony.i18n.getLocalizedString("i18n.errorMsgs.validUsernamealert");
    i18n_emptyPasswordalert = kony.i18n.getLocalizedString("i18n.errorMsgs.emptyPasswordalert");
  	i18n_PasswordMismatchalert = kony.i18n.getLocalizedString("i18n.errorMsgs.PasswordMismatchalert");	
  	i18n_Passwordsuniquealert =kony.i18n.getLocalizedString("i18n.errorMsgs.Passwordsuniquealert");
  	i18n_validPasswordalert = kony.i18n.getLocalizedString("i18n.errorMsgs.validPasswordalert");
    i18n_EmailorPhoneemptyalert= kony.i18n.getLocalizedString("i18n.errorMsgs.EmailorPhoneemptyalert");
    i18n_validEmailalert =kony.i18n.getLocalizedString("i18n.errorMsgs.validEmailalert");
    i18n_validSecondaryEmailalert= kony.i18n.getLocalizedString("i18n.errorMsgs.validSecondaryEmailalert");
    i18n_imagenotSelected= kony.i18n.getLocalizedString("i18n.errorMsgs.imagenotSelected");
    i18n_mediaGalleryerror=kony.i18n.getLocalizedString("i18n.errorMsgs.mediaGalleryerror");
    i18n_devRegSuccess=kony.i18n.getLocalizedString("i18n.commomerror.devDeRegSuccess");
    i18n_editProfileHeader=kony.i18n.getLocalizedString("i18n.settings.EditProfile");
    i18n_editPasswordHeader=kony.i18n.getLocalizedString("i18n.settings.editPassword");
    i18n_editUnameHeader = kony.i18n.getLocalizedString("i18n.settings.editUsername");
    i18n_draftMessages = kony.i18n.getLocalizedString("i18n.Messages.Deletemsg");
    i18n_sentMessages = kony.i18n.getLocalizedString("i18n.messages.sentMessages");
    i18n_deletedMessages = kony.i18n.getLocalizedString("i18n.messages.deletedMessages");
    i18n_myMessages=kony.i18n.getLocalizedString("i18n.messages.myMessages");
    i18n_noDescription=kony.i18n.getLocalizedString("i18n.Messages.noDescription");
    i18n_noSubject = kony.i18n.getLocalizedString("i18n.Messages.noSubject");
    i18n_sentOn = kony.i18n.getLocalizedString("i18n.messages.sentOn");
    i18n_ReceivedOn = kony.i18n.getLocalizedString("i18n.messages.recievedOn");
    i18n_deletedOn =  kony.i18n.getLocalizedString("i18n.messages.deletedOn");
    i18n_createdOn = kony.i18n.getLocalizedString("i18n.messages.createdOn");
    i18n_selectSubcategory=kony.i18n.getLocalizedString("i18n.messages.selectSubcategory");
    i18n_referenceId=kony.i18n.getLocalizedString("i18n.common.ReferenceId");
    i18n_processingTransaction=kony.i18n.getLocalizedString("i18n.success.processingTransaction");
    i18n_successtext=kony.i18n.getLocalizedString("i18n.common.successText");
    i18n_termsnConditions = kony.i18n.getLocalizedString("i18n.opening_account.termsAndConditions");
    i18n_validAmountalert = kony.i18n.getLocalizedString("i18n.deposits.ValidAmountAlert");
    i18n_uploadImagesalert = kony.i18n.getLocalizedString("i18n.deposits.ChequesAlert");
    i18n_selectStateAlert = kony.i18n.getLocalizedString("i18n.OpenNewAccount.selectStateAlert");
    i18n_primaryFieldsAlert= kony.i18n.getLocalizedString("i18n.OpenNewAccount.primaryFieldsAlert");
    i18n_validSSNalert = kony.i18n.getLocalizedString("i18n.OpenNewAccount.validSSNAlert");
    i18n_answerSecretQuestns = kony.i18n.getLocalizedString("i18n.opening_account.answerSecretQuestions");
    i18n_viewApplicationForm = kony.i18n.getLocalizedString("i18n.opening_account.viewApplicationForm");
	i18n_availableBalance = kony.i18n.getLocalizedString("i18n.deposit.availableBalance");
  	i18n_oneTIme = kony.i18n.getLocalizedString("i18n.transfer.oneTime");
  	i18n_daily = kony.i18n.getLocalizedString("i18n.transfers.Daily");
  	i18n_weeklyOnce = kony.i18n.getLocalizedString("i18n.transfers.WeeklyOnce");
  	i18n_every2Weeks = kony.i18n.getLocalizedString("i18n.transfers.Every2Weeks");
  	i18n_monthlyOnce = kony.i18n.getLocalizedString("i18n.transfers.MonthlyOnce");
  	i18n_cancelBillPay = kony.i18n.getLocalizedString("i18n.transfers.CancelBillPay");
  	i18n_savingsAccount = kony.i18n.getLocalizedString("i18n.common.savingsAccount");
  	i18n_billPaymentTo = kony.i18n.getLocalizedString("i18n.transfers.BillPaymentTo");
  	i18n_repeatBillPay = kony.i18n.getLocalizedString("i18n.transfer.repeatBillPay");
  	i18n_P2PTransferTo = kony.i18n.getLocalizedString("i18n.transfers.P2PTransferTo");
  	i18n_repeatTransfer = kony.i18n.getLocalizedString("i18n.transfers.RepeatTransfer");
  	i18n_transferTo = kony.i18n.getLocalizedString("i18n.transfers.TransferTo");
  	i18n_recentTransactions = kony.i18n.getLocalizedString("i18n.common.recentTransactions");
  	i18n_transactionDate = kony.i18n.getLocalizedString("i18n.transfers.TransactionDate");
  	i18n_scheduledTransactions = kony.i18n.getLocalizedString("i18n.overview.scheduledTransactions");
  	i18n_next = kony.i18n.getLocalizedString("i18n.login.next");
  	i18n_times = kony.i18n.getLocalizedString("i18n.transfers.Times");
  	i18n_to = kony.i18n.getLocalizedString("i18n.transfer.to");
  	i18n_ok = kony.i18n.getLocalizedString("i18n.settings.ok");
  	i18n_TRANSFER = kony.i18n.getLocalizedString("i18n.transfers.TRANSFER...");
  	i18n_repeatP2P = kony.i18n.getLocalizedString("i18n.transfer.RepeatP2P");
  	i18_payAPerson = kony.i18n.getLocalizedString("i18n.transfer.payAPerson");
  	i18n_pay = kony.i18n.getLocalizedString("i18n.transfer.pay");
  	i18n_payBill = kony.i18n.getLocalizedString("i18n.transfer.payBill");
  	i18n_scheduledForC = kony.i18n.getLocalizedString("i18n.common.scheduledForC");
  	i18n_transactionDateC = kony.i18n.getLocalizedString("i18n.transfer.transactionDateC");
    i18n_currentBalance = kony.i18n.getLocalizedString("i18n.common.currentBalance");
    i18n_outStandingBalance =  kony.i18n.getLocalizedString("i18n.common.outStandingBalance");
    i18n_cancel = kony.i18n.getLocalizedString("i18n.common.cancel");
  	i18n_Disable = kony.i18n.getLocalizedString("i18n.login.Disable");
    i18n_turnOffRememberMe= kony.i18n.getLocalizedString("i18n.login.rememberMeAlert");
    i18n_disableTouchId = kony.i18n.getLocalizedString("i18n.login.DisableTouchId");
    i18n_UpgradeofApp = kony.i18n.getLocalizedString("i18n.common.UpgradeofApp");
    i18n_Upgrade = kony.i18n.getLocalizedString("i18n.common.Upgrade");
    i18n_UpgradeApp = kony.i18n.getLocalizedString("i18n.common.UpgradeApp");
    i18n_UpgradeAppAlert = kony.i18n.getLocalizedString("i18n.common.UpgradeAppAlert");
    i18n_enrollSuccessAlert=kony.i18n.getLocalizedString("i18n.login.enrollSuccessAlert");
    i18n_appLaunchError=kony.i18n.getLocalizedString("i18n.errorMsg.appLaunchError");
    i18n_deviceConnectionError = kony.i18n.getLocalizedString("i18n.errorMsg.deviceConnectionError");
    i18n_retake = kony.i18n.getLocalizedString("i18n.deposit.retake");
    i18n_takePhoto = kony.i18n.getLocalizedString("i18n.deposit.takePhoto");
	i18n_sameAccountAlert = kony.i18n.getLocalizedString("i18n.transfers.sameAccountAlert");
  	i18n_validAmountAlert = kony.i18n.getLocalizedString("i18n.deposits.ValidAmountAlert");
  	i18n_unsufficientAmountAlert = kony.i18n.getLocalizedString("i18n.transfers.unsufficientAmountAlert");
  	i18n_selectToAccountAlert = kony.i18n.getLocalizedString("i18n.transfers.selectToAccountAlert");
  	i18n_selectFromAccountAlert = kony.i18n.getLocalizedString("i18n.transfers.selectFromAccountAlert");
  	i18n_selectTonFromAccountAlert = kony.i18n.getLocalizedString("i18n.transfers.selectTonFromAccountAlert");
  	i18n_cancelTransferAlert = kony.i18n.getLocalizedString("i18n.transfers.cancelTransferAlert");
  	i18n_cancelAlert = kony.i18n.getLocalizedString("i18n.transfers.cancelAlert");
  	i18n_btnInfo = kony.i18n.getLocalizedString("i18n.opening_account.btnInfo");
  	i18n_YES = kony.i18n.getLocalizedString("i18n.common.YES");
  	i18n_NO = kony.i18n.getLocalizedString("i18n.common.NO");
  	i18n_default = kony.i18n.getLocalizedString("i18n.common.default");
  	i18n_Once = kony.i18n.getLocalizedString("i18n.transfers.Once");
  	i18n_Weekly = kony.i18n.getLocalizedString("i18n.transfers.Weekly");
  	i18n_BiWeekly = kony.i18n.getLocalizedString("i18n.transfers.BiWeekly");
  	i18n_Monthly = kony.i18n.getLocalizedString("i18n.transfers.Monthly");
  	i18n_transactionUpdateAlert = kony.i18n.getLocalizedString("i18n.transfers.transactionUpdateAlert");
  	i18n_selectCountryAlert = kony.i18n.getLocalizedString("i18n.billPay.selectCountryAlert");
  	i18n_enterBeneficiaryNameAlert = kony.i18n.getLocalizedString("i18n.billPay.enterBeneficiaryNameAlert");
  	i18n_enterAccountNumberAlert = kony.i18n.getLocalizedString("i18n.billPay.enterAccountNumberAlert");
  	i18n_enterswiftCodeAlert = kony.i18n.getLocalizedString("i18n.billPay.enterswiftCodeAlert");
  	i18n_enterRoutingNumberAlert = kony.i18n.getLocalizedString("i18n.billPay.enterRoutingNumberAlert");
  	i18n_currentBalance = kony.i18n.getLocalizedString("i18n.common.currentBalance");
    i18n_outStandingBalance =  kony.i18n.getLocalizedString("i18n.common.outStandingBalance");
    i18n_cancel = kony.i18n.getLocalizedString("i18n.common.cancel");
  	i18n_notes = kony.i18n.getLocalizedString("i18n.common.notes");
  	i18n_scheduledFor = kony.i18n.getLocalizedString("i18n.common.scheduledFor");
  	i18n_cancelTransferAlert = kony.i18n.getLocalizedString("i18n.transfers.cancelTransferAlert");
  	i18n_ScheduledBillDetails = kony.i18n.getLocalizedString("i18n.billPay.ScheduledBillDetails");
  	i18n_CompletedBillDetails = kony.i18n.getLocalizedString("i18n.billPay.CompletedBillDetails");
  	i18n_fieldsMandatory = kony.i18n.getLocalizedString("i18n.billPay.fieldsMandatory");
  	i18n_AccountMismatchAlert = kony.i18n.getLocalizedString("i18n.billPay.AccountMismatchAlert");
  	i18n_editP2PPerson = kony.i18n.getLocalizedString("i18n.common.editP2PPerson");
  	i18n_editTransfer = kony.i18n.getLocalizedString("i18n.common.editTransfer");
  	i18n_noContacts = kony.i18n.getLocalizedString("i18n.common.noContacts");
  	i18n_enterZipCode = kony.i18n.getLocalizedString("i18n.common.enterZipCode");
  	i18n_billPayEdit = kony.i18n.getLocalizedString("i18n.common.billPayEdit");
  	i18n_PendingTransaction = kony.i18n.getLocalizedString("i18n.common.PendingTransaction");
  	i18n_PendingTransactionText = kony.i18n.getLocalizedString("i18n.common.PendingTransactionText");
  	i18n_TransferScheduled = kony.i18n.getLocalizedString("i18n.common.TransferScheduled");
  	i18n_depositPending = kony.i18n.getLocalizedString("i18n.common.depositPending");
  	i18n_companyNameAlert = kony.i18n.getLocalizedString("i18n.billPay.companyNameAlert");
  	i18n_reenterAccountNumberAlert = kony.i18n.getLocalizedString("i18n.billPay.reenterAccountNumberAlert");
    i18n_enterLocation =  kony.i18n.getLocalizedString("i18n.opening_account.enterLocation");
    i18n_pickaproduct = kony.i18n.getLocalizedString("i18n.more.pickAProduct");
    i18n_msgReply = kony.i18n.getLocalizedString("i18n.messages.reply");
    i18n_msgDelete = kony.i18n.getLocalizedString("i18n.Messages.Delete");
    i18n_Card = kony.i18n.getLocalizedString("i18n.cards.Card");
    i18n_CardHolder = kony.i18n.getLocalizedString("i18n.cards.CardHolderC");
    i18n_CardValidThru = kony.i18n.getLocalizedString("i18n.cards.ValidThroughC");
    i18n_cardNumberX = kony.i18n.getLocalizedString("i18n.cards.cardNumberxC");
    i18n_requestPinChange = kony.i18n.getLocalizedString("i18n.cards.RequestingPINChange");
    i18n_Cancelling = kony.i18n.getLocalizedString("i18n.cards.Cancelling");
    i18n_StolenorLost = kony.i18n.getLocalizedString("i18n.cards.Stolen/Lost");
    i18n_Replacing = kony.i18n.getLocalizedString("i18n.cards.Replacing");
    i18n_Deactivating = kony.i18n.getLocalizedString("i18n.cards.Deactivating");
    i18n_Activating = kony.i18n.getLocalizedString("i18n.cards.Activating");
    i18n_CardTypeC = kony.i18n.getLocalizedString("i18n.cards.CardTypec");
    i18n_DeactivateCard = kony.i18n.getLocalizedString("i18n.cards.DeactivateCard");
    i18n_ActivateCard = kony.i18n.getLocalizedString("i18n.cards.ActivateCard");
    i18n_DeactivateCardInfo = kony.i18n.getLocalizedString("i18n.cards.DeActivateCardInfo");
    i18n_cancelCardInfo =  kony.i18n.getLocalizedString("i18n.cards.CancelCardInfo");
    i18n_ReportCardInfo=kony.i18n.getLocalizedString("i18n.cards.ReportCardInfo");
    i18n_ReplacementCardInfo = kony.i18n.getLocalizedString("i18n.cards.ReplacementCardInfo");
    i18n_Confirmationalert = kony.i18n.getLocalizedString("i18n.cards.Confirmation");
    i18n_Call = kony.i18n.getLocalizedString("i18n.cards.CALL");
    i18n_InstructCardsLost = kony.i18n.getLocalizedString("i18n.cards.InstructCardsLost");
    i18n_InstructPinChange=kony.i18n.getLocalizedString("i18n.cards.InstructPinChange");
    i18n_cardDeactivated=kony.i18n.getLocalizedString("i18n.cards.cardDeactivated");
    i18n_cardactivated=kony.i18n.getLocalizedString("i18n.cards.cardactivated");
    i18n_cardCancelled=kony.i18n.getLocalizedString("i18n.cards.cardCancelled");
    i18n_replacementReq=kony.i18n.getLocalizedString("i18n.cards.replacementReq");
    i18n_openaccountId = kony.i18n.getLocalizedString("i18n.opening_account.yourIDis");
    i18n_contactMsg=kony.i18n.getLocalizedString("i18n.newAccount.contactMsg");
    i18n_workingDays=kony.i18n.getLocalizedString("i18n.common.workingDays");
	i18n_alertInvalidCred = kony.i18n.getLocalizedString("i18n.login.alertInvalidCred");
  	i18n_alertAuthCancelUser = kony.i18n.getLocalizedString("i18n.login.alertAuthCancelUser");
  	i18n_alertAuthCancelBackBtn = kony.i18n.getLocalizedString("i18n.login.alertAuthCancelBackBtn");
  	i18n_alertAuthCancelSystem = kony.i18n.getLocalizedString("i18n.login.alertAuthCancelSystem");
  	i18n_alertPasscodeNotSet = kony.i18n.getLocalizedString("i18n.login.alertPasscodeNotSet");
  	i18n_alertTouchIdUnavailable = kony.i18n.getLocalizedString("i18n.login.alertTouchIdUnavailable");
  	i18n_alertTouchIdNotEnrolled = kony.i18n.getLocalizedString("i18n.login.alertTouchIdNotEnrolled");
  	i18n_alertTouchIdAuthFailed = kony.i18n.getLocalizedString("i18n.login.alertTouchIdAuthFailed");
    i18n_accountPreviewAlert=kony.i18n.getLocalizedString("i18n.login.accountPreviewAlert");
    i18n_lastMonth=kony.i18n.getLocalizedString("i18n.charts.lastMonthC");
    i18n_thisMonth=kony.i18n.getLocalizedString("i18n.charts.thisMonthC");
    i18n_cashFlow=kony.i18n.getLocalizedString("i18n.overview.cashFlow");
    i18n_nativeTouchId=kony.i18n.getLocalizedString("i18n.login.nativeTouchIdInstrn");
	i18n_unfilledData = kony.i18n.getLocalizedString("i18n.newaccount.unfilledData");
  	i18n_Error = kony.i18n.getLocalizedString("i18n.common.Error");
  	i18n_DistanceUnknown = kony.i18n.getLocalizedString("i18n.maps.DistanceUnknown");
  	i18n_turnOnLocationAlert = kony.i18n.getLocalizedString("i18n.maps.turnOnLocationAlert");
  	i18n_settings = kony.i18n.getLocalizedString("i18n.settings.settings");
  	i18n_noatmorBranchesFound = kony.i18n.getLocalizedString("i18n.locateus.noatmorBranchesFound");
  	i18n_Call = kony.i18n.getLocalizedString("i18n.common.Call");
  	i18n_noDirections = kony.i18n.getLocalizedString("i18n.maps.noDirections");
  	i18n_defaultDirectionListVA = kony.i18n.getLocalizedString("i18n.common.Map.defaultDirectionListVA.ValueVA");
    i18n_transactionFailed=kony.i18n.getLocalizedString("i18n.common.transactionFailed");
    i18n_FailedMsg=kony.i18n.getLocalizedString("i18n.common.sorryForinconvenience");
    i18n_select=kony.i18n.getLocalizedString("i18n.common.Select");
    i18n_confirmSignOut=kony.i18n.getLocalizedString("i18n.common.confirmSignOut");
    i18n_signOut=kony.i18n.getLocalizedString("i18n.common.signOut");
    i18n_signOutAlert=kony.i18n.getLocalizedString("i18n.common.signOutAlert");
    i18n_Yeslbl=kony.i18n.getLocalizedString("i18n.common.alertYes");
    i18n_Nolbl=kony.i18n.getLocalizedString("i18n.common.alertNo");
    i18n_depositCancel=kony.i18n.getLocalizedString("i18n.deposits.depositCancel");
    i18n_cancelDepositAlert=kony.i18n.getLocalizedString("i18n.deposits.cancelDepositAlert");
    i18n_depositSuccessMsg =kony.i18n.getLocalizedString("i18n.deposits.succesMessage");

}   


