var i18n_AccountPreview;
var i18n_TouchID;
var i18n_devRegistration;
var i18n_LoginSettings;
var i18n_GeneralSettings;
var i18n_ProfilenAlerts;
var i18n_MyProfile;
var i18n_Alerts;
var i18n_ForTransfers;
var i18n_ForDeposits;
var i18n_ForPayments;
var i18n_Hi;
var i18n_lastSignin;
var i18n_touchIdHeader;
var i18n_defaultPage;
var i18n_preferredAccounts;
var i18n_onLabel;
var i18n_offLabel;
var i18n_differentUsername;
var i18n_validUsernamealert;
var i18n_emptyPasswordalert;
var i18n_PasswordMismatchalert;
var i18n_Passwordsuniquealert;
var i18n_validPasswordalert;
var i18n_EmailorPhoneemptyalert;
var i18n_validEmailalert;
var i18n_validSecondaryEmailalert;
var i18n_imagenotSelected;
var i18n_mediaGalleryerror;
var i18n_devRegSuccess;
var i18n_alertsFor;
var i18n_select;
var i18n_sentOn;
var i18n_deletedOn;
var i18n_recievedOn;
var i18n_onLabel;
var i18n_offLabel;
var i18n_differentUsername;
var i18n_validUsernamealert;
var i18n_emptyPasswordalert;
var i18n_PasswordMismatchalert;
var i18n_Passwordsuniquealert;
var i18n_validPasswordalert;
var i18n_EmailorPhoneemptyalert;
var i18n_validEmailalert;
var i18n_validSecondaryEmailalert;
var i18n_imagenotSelected;
var i18n_mediaGalleryerror;
var i18n_devRegSuccess;
var i18n_alertsFor;
var i18n_select;
var i18n_sentOn;
var i18n_deletedOn;
var i18n_recievedOn;
var i18n_noDescription;
var i18n_noSubject;
var i18n_call;
var i18n_cancelC;
var i18n_of;
var i18n_used;
var i18n_myMessages;
var i18n_selectSubcategory;
var i18n_availableBalance;
var i18n_takePhoto;
var i18n_retake;
var i18n_uploadImagesalert;
var i18n_pendingDeposit;
var i18n_recentTransactions;
var i18n_notesc;
var i18n_billPaymentTo;
var i18n_repeatBillPay;
var i18n_p2pTransferTo;
var i18n_repeatTransfer;
var i18n_transferTo;
var i18n_transactionDate;
var i18n_scheduledTransactions;
var i18n_scheduledForC;
var i18n_next;
var i18n_Times;
var i18n_to;
var i18n_cancelBillPay;
var i18n_cancelTransferAlert;
var i18n_repeatTransaction;
var i18n_validSSNAlert;
var i18n_emailNotValid;
var i18n_OK;
var i18n_unfilledData;
var i18n_primaryFieldsAlert;
var i18n_selectStateAlert;
var i18n_cancel;
var i18n_yourIDis;
var i18n_upgradeOfApp; 
var i18n_upgrade;
var i18n_instrUpgrade;
var i18n_qstnUpgrade;
var i18n_disable;
var i18n_disableTouchId;
var i18n_disableTouchIdMessage;
var i18n_newTransfer;
var i18n_add;
var i18n_sameAccountAlert;
var i18n_notValidAmount;
var i18n_selectToAccountAlert;
var   i18n_selectFromAccountAlert;
var  i18n_selectTonFromAccountAlert;
var i18n_oneTime;
var i18n_daily;
var i18n_weeklyOnce;
var i18n_every2Weeks;
var i18n_monthlyOnce;
var i18n_cancelAlert;
var i18n_Info;
var i18n_yes;
var i18n_no;
var i18n_fromAndToAccountSame;
var i18n_processingTransaction;
var i18n_referenceId;
var i18n_transactionFailed;
var i18n_sorryForinconvenience;
var i18n_card;
var i18n_RequestingPINChange;
var i18n_Cancelling;
var i18n_Stolen;
var i18n_Replacing;
var i18n_Deactivating;
var i18n_Activating;
var i18n_Confirmation;
var i18n_InstructCardsLost;
var i18n_InstructPinChange;
var i18n_ActivateCard;
var i18n_DeactivateCard;
var i18n_cardDeactivated;
var i18n_cardactivated;
var i18n_cardCancelled;
var i18n_replacementReq;
var i18n_workingDays;
var i18n_DeActivateCardInfo;
var i18n_CancelCardInfo;
var i18n_ReportCardInfo;
var i18n_ReplacementCardInfo;
var i18n_CardHolderC;
var i18n_Card;
var i18n_cardNumberxC;
var i18n_CardTypec;
var i18n_ValidThroughC;
var i18n_selectCountryAlert;
var i18n_enterAccountNumberAlert;
var i18n_enterRoutingNumberAlert;
var i18n_enterswiftCodeAlert;
var i18n_payBill;
var i18n_editPayBill;
var i18n_outStandingBalance;
var i18n_CompletedBillDetails;
var i18n_ScheduledBillDetails;
var i18n_companyNameAlert;
var i18n_payeeNickNameAlert;
var  i18n_reenterAccountNumberAlert;
var  i18n_enterZipCode;
var i18n_accountNumberReAccountNumberAlert;
var i18n_currentBalance;
var i18n_billPayEdit;
var i18n_pay;
var i18n_processingTransaction;
var i18n_successText;
var i18n_payAPerson;
var i18n_asOfToday;
var i18n_PaymentDueDateg;
var i18n_maturityDate;
var i18n_lastStatementBalanceg;
var i18n_cashFlow;
var i18n_lastMonthC;
var i18n_thisMonthC;
var i18n_swipeMsg;
var i18n_appLaunchError;
var i18n_deviceConnectionError;
var i18n_asOf;
var i18n_touchIdMsg;
var i18n_alertInvalidCred;
var i18n_alertAuthCancelUser;
var i18n_alertAuthCancelBackBtn;
var i18n_alertAuthCancelSystem;
var i18n_alertPasscodeNotSet;
var i18n_alertTouchIdUnavailable;
var i18n_alertTouchIdNotEnrolled;
var i18n_alertTouchIdAuthFailed;
var i18n_accountPreviewAlert;
var i18n_dailError;
var i18n_securityAnsValidated;
var i18n_turnOnLocationAlert;
var i18n_DistanceUnknown;
var i18n_edit;
var i18n_repeatP2P;
var i18n_depositSuccMsg;
var i18n_searchTransactions;
var i18n_viewAcntInfo;
var i18n_viewAcntStatements;
var i18n_touchIdalertAndroid;
var i18n_touchIdalertAndroidMsg;
var i18n_goodMorning;
var i18n_goodEvening;
var i18n_goodAfternoon;
function generatei18nKeys()
{
    i18n_securityAnsValidated = kony.i18n.getLocalizedString("i18n.commomerror.securityAnsValidated");
	i18n_AccountPreview = kony.i18n.getLocalizedString("i18n.common.accountPreview");
    i18n_TouchID = kony.i18n.getLocalizedString("i18n.common.touchID");
    i18n_devRegistration =kony.i18n.getLocalizedString("i18n.login.deviceRegisteration");
    i18n_LoginSettings = kony.i18n.getLocalizedString("i18n.settings.loginSettingsC");
    i18n_GeneralSettings = kony.i18n.getLocalizedString("i18n.settings.generalSettingsC");
    i18n_ProfilenAlerts =  kony.i18n.getLocalizedString("i18n.settings.profileAndAlertsC");
    i18n_MyProfile = kony.i18n.getLocalizedString("i18n.settings.myProfile");
    i18n_Alerts = kony.i18n.getLocalizedString("i18n.settings.alerts");
    i18n_ForTransfers = kony.i18n.getLocalizedString("i18n.settings.forTransfers");
    i18n_ForDeposits = kony.i18n.getLocalizedString("i18n.settings.forDeposits");
    i18n_ForPayments = kony.i18n.getLocalizedString("i18n.settings.forPayments");
    i18n_Hi= kony.i18n.getLocalizedString("i18n.common.hic");
    i18n_lastSignin = kony.i18n.getLocalizedString("i18n.common.youLastSignedOnAt");
    i18n_touchIdHeader=kony.i18n.getLocalizedString("i18n.touchId.headingwithoutBank");
  	i18n_defaultPage = kony.i18n.getLocalizedString("i18n.settings.defaultPage");
	i18n_preferredAccounts = kony.i18n.getLocalizedString("i18n.settings.preferredAccounts");
	i18n_onLabel= kony.i18n.getLocalizedString("i18n.settings.on");
    i18n_offLabel = kony.i18n.getLocalizedString("i18n.settings.off");
    i18n_differentUsername = kony.i18n.getLocalizedString("i18n.errorMsgs.differentUsername");
    i18n_validUsernamealert = kony.i18n.getLocalizedString("i18n.errorMsgs.validUsernamealert");
    i18n_emptyPasswordalert = kony.i18n.getLocalizedString("i18n.errorMsgs.emptyPasswordalert");
  	i18n_PasswordMismatchalert = kony.i18n.getLocalizedString("i18n.errorMsgs.PasswordMismatchalert");	
  	i18n_Passwordsuniquealert =kony.i18n.getLocalizedString("i18n.errorMsgs.Passwordsuniquealert");
  	i18n_validPasswordalert = kony.i18n.getLocalizedString("i18n.errorMsgs.validPasswordalert");
    i18n_EmailorPhoneemptyalert= kony.i18n.getLocalizedString("i18n.errorMsgs.EmailorPhoneemptyalert");
    i18n_validEmailalert =kony.i18n.getLocalizedString("i18n.errorMsgs.validEmailalert");
    i18n_validSecondaryEmailalert= kony.i18n.getLocalizedString("i18n.errorMsgs.validSecondaryEmailalert");
    i18n_imagenotSelected= kony.i18n.getLocalizedString("i18n.errorMsgs.imagenotSelected");
    i18n_mediaGalleryerror=kony.i18n.getLocalizedString("i18n.errorMsgs.mediaGalleryerror");
    i18n_devRegSuccess=kony.i18n.getLocalizedString("i18n.commomerror.devDeRegSuccess");
	i18n_alertsFor=kony.i18n.getLocalizedString("i18n.settings.alertsFor");
	i18n_select = kony.i18n.getLocalizedString("i18n.settings.select");
	i18n_sentOn = kony.i18n.getLocalizedString("i18n.messages.sentOn");
    i18n_deletedOn = kony.i18n.getLocalizedString("i18n.messages.deletedOn");
    i18n_recievedOn = kony.i18n.getLocalizedString("i18n.messages.recievedOn");
	i18n_noDescription=kony.i18n.getLocalizedString("i18n.Messages.noDescription");
	i18n_noSubject = kony.i18n.getLocalizedString("i18n.Messages.noSubject");
	i18n_call = kony.i18n.getLocalizedString("i18n.cards.CALL");
    i18n_cancelC = kony.i18n.getLocalizedString("i18n.common.cancelC"); 
    i18n_of = kony.i18n.getLocalizedString("i18n.common.of");
    i18n_used = kony.i18n.getLocalizedString("i18n.common.used");
    i18n_myMessages = kony.i18n.getLocalizedString("i18n.messages.myMessages");
    i18n_selectSubcategory=kony.i18n.getLocalizedString("i18n.messages.selectSubcategory");
    i18n_availableBalance=kony.i18n.getLocalizedString("i18n.deposit.availableBalance");
    i18n_takePhoto = kony.i18n.getLocalizedString("i18n.deposit.takePhoto");
    i18n_retake =  kony.i18n.getLocalizedString("i18n.deposit.retake");
    i18n_uploadImagesalert = kony.i18n.getLocalizedString("i18n.deposits.ChequesAlert");
    i18n_pendingDeposit =kony.i18n.getLocalizedString("i18n.deposit.pendingDeposit");
    i18n_recentTransactions =kony.i18n.getLocalizedString("i18n.common.recentTransactions");
    i18n_notesc =kony.i18n.getLocalizedString("i18n.common.notesc");
    i18n_billPaymentTo =kony.i18n.getLocalizedString("i18n.transfers.BillPaymentTo");
    i18n_repeatBillPay =kony.i18n.getLocalizedString("i18n.transfer.repeatBillPay");
    i18n_p2pTransferTo =kony.i18n.getLocalizedString("i18n.transfers.P2PTransferTo");
    i18n_repeatTransfer =kony.i18n.getLocalizedString("i18n.transfers.RepeatTransfer");
    i18n_transferTo =kony.i18n.getLocalizedString("i18n.transfers.TransferTo");
  	i18n_transactionDate =kony.i18n.getLocalizedString("i18n.transfer.transactionDateC");
  	i18n_scheduledTransactions =kony.i18n.getLocalizedString("i18n.overview.scheduledTransactions");
  	i18n_scheduledForC =kony.i18n.getLocalizedString("i18n.common.scheduledForC");
  	i18n_next =kony.i18n.getLocalizedString("i18n.login.next");
  	i18n_Times =kony.i18n.getLocalizedString("i18n.transfers.Times");
  	i18n_to =kony.i18n.getLocalizedString("i18n.transfer.to");
  	i18n_cancelBillPay =kony.i18n.getLocalizedString("i18n.transfers.CancelBillPay");
  	i18n_cancelTransferAlert =kony.i18n.getLocalizedString("i18n.transfers.cancelTransferAlert");
  	i18n_repeatTransaction =kony.i18n.getLocalizedString("i18n.transfer.repeatTransaction");
    i18n_validSSNAlert =kony.i18n.getLocalizedString("i18n.OpenNewAccount.validSSNAlert");
    i18n_emailNotValid =kony.i18n.getLocalizedString("i18n.newaccount.emailNotValid");
    i18n_OK =kony.i18n.getLocalizedString("i18n.settings.ok");
    i18n_primaryFieldsAlert=kony.i18n.getLocalizedString("i18n.OpenNewAccount.primaryFieldsAlert");
    i18n_unfilledData =kony.i18n.getLocalizedString("i18n.newaccount.unfilledData");
    i18n_selectStateAlert =kony.i18n.getLocalizedString("i18n.OpenNewAccount.selectStateAlert");
    i18n_cancel = kony.i18n.getLocalizedString("i18n.common.cancel");
    i18n_yourIDis =kony.i18n.getLocalizedString("i18n.opening_account.yourIDis");
    i18n_validSSNAlert =kony.i18n.getLocalizedString("i18n.OpenNewAccount.validSSNAlert");
    i18n_emailNotValid =kony.i18n.getLocalizedString("i18n.newaccount.emailNotValid");
    i18n_OK =kony.i18n.getLocalizedString("i18n.settings.ok");
    i18n_primaryFieldsAlert=kony.i18n.getLocalizedString("i18n.OpenNewAccount.primaryFieldsAlert");
    i18n_unfilledData =kony.i18n.getLocalizedString("i18n.newaccount.unfilledData");
    i18n_selectStateAlert =kony.i18n.getLocalizedString("i18n.OpenNewAccount.selectStateAlert");
    i18n_cancel = kony.i18n.getLocalizedString("i18n.common.cancel");
	i18n_upgradeOfApp = kony.i18n.getLocalizedString("i18n.appUpgrade.upgradeOfAnApp");
    i18n_upgrade = kony.i18n.getLocalizedString("i18n.appUpgrade.upgrade");
    i18n_instrUpgrade = kony.i18n.getLocalizedString("i18n.appUpgrade.instrUpgrade");
    i18n_qstnUpgrade = kony.i18n.getLocalizedString("i18n.appUpgrade.qstnUpgrade");
    i18n_disable = kony.i18n.getLocalizedString("i18n.common.disable");
 	i18n_disableTouchId = kony.i18n.getLocalizedString("i18n.touchId.disableOfTouchId");
    i18n_disableTouchIdMessage = kony.i18n.getLocalizedString("i18n.touchId.disableMessageOfTouchd");
	i18n_newTransfer =kony.i18n.getLocalizedString("i18n.transfer.newTransfer");
    i18n_add = kony.i18n.getLocalizedString("i18n.common.Add");
    i18n_sameAccountAlert = kony.i18n.getLocalizedString("i18n.transfers.sameAccountAlert");
    i18n_notValidAmount = kony.i18n.getLocalizedString("i18n.transfers.notValidAmount");
    i18n_selectToAccountAlert = kony.i18n.getLocalizedString("i18n.transfers.selectToAccountAlert");
    i18n_selectFromAccountAlert = kony.i18n.getLocalizedString("i18n.transfers.selectFromAccountAlert");
    i18n_selectTonFromAccountAlert = kony.i18n.getLocalizedString("i18n.transfers.selectTonFromAccountAlert");
    i18n_oneTime =kony.i18n.getLocalizedString("i18n.transfer.oneTime"); 
    i18n_daily =kony.i18n.getLocalizedString("i18n.transfers.Daily"); 
    i18n_weeklyOnce =kony.i18n.getLocalizedString("i18n.transfers.WeeklyOnce"); 
    i18n_every2Weeks =kony.i18n.getLocalizedString("i18n.transfers.Every2Weeks"); 
    i18n_monthlyOnce =kony.i18n.getLocalizedString("i18n.transfers.MonthlyOnce"); 
    i18n_cancelAlert =kony.i18n.getLocalizedString("i18n.transfers.cancelAlert"); 
    i18n_Info =kony.i18n.getLocalizedString("i18n.opening_account.btnInfo"); 
    i18n_yes =kony.i18n.getLocalizedString("i18n.common.YES"); 
    i18n_no =kony.i18n.getLocalizedString("i18n.common.NO"); 
    i18n_fromAndToAccountSame =kony.i18n.getLocalizedString("i18n.transfers.fromAndToAccountSame"); 
    i18n_processingTransaction =kony.i18n.getLocalizedString("i18n.success.processingTransaction"); 
    i18n_referenceId =kony.i18n.getLocalizedString("i18n.common.ReferenceId"); 
    i18n_transactionFailed =kony.i18n.getLocalizedString("i18n.common.transactionFailed"); 
    i18n_sorryForinconvenience =kony.i18n.getLocalizedString("i18n.common.sorryForinconvenience");
    i18n_editTransfer =kony.i18n.getLocalizedString("i18n.common.editTransfer");
    i18n_card =kony.i18n.getLocalizedString("i18n.cards.card");
    i18n_RequestingPINChange =kony.i18n.getLocalizedString("i18n.cards.RequestingPINChange");
    i18n_Cancelling =kony.i18n.getLocalizedString("i18n.cards.Cancelling");
    i18n_Stolen =kony.i18n.getLocalizedString("i18n.cards.Stolen/Lost");
    i18n_Replacing =kony.i18n.getLocalizedString("i18n.cards.Replacing");
    i18n_Deactivating =kony.i18n.getLocalizedString("i18n.cards.Deactivating");
    i18n_Activating =kony.i18n.getLocalizedString("i18n.cards.Activating");
    i18n_Confirmation =kony.i18n.getLocalizedString("i18n.cards.Confirmation");
    i18n_InstructCardsLost =kony.i18n.getLocalizedString("i18n.cards.InstructCardsLost");
    i18n_InstructPinChange =kony.i18n.getLocalizedString("i18n.cards.InstructPinChange");
    i18n_ActivateCard =kony.i18n.getLocalizedString("i18n.cards.ActivateCard");
    i18n_DeactivateCard =kony.i18n.getLocalizedString("i18n.cards.DeactivateCard");
    i18n_cardDeactivated =kony.i18n.getLocalizedString("i18n.cards.cardDeactivated");
    i18n_cardactivated =kony.i18n.getLocalizedString("i18n.cards.cardactivated");
    i18n_cardCancelled =kony.i18n.getLocalizedString("i18n.cards.cardCancelled");
    i18n_replacementReq =kony.i18n.getLocalizedString("i18n.cards.replacementReq");
    i18n_workingDays =kony.i18n.getLocalizedString("i18n.common.workingDays");
    i18n_DeActivateCardInfo =kony.i18n.getLocalizedString("i18n.cards.DeActivateCardInfo");
    i18n_CancelCardInfo =kony.i18n.getLocalizedString("i18n.cards.CancelCardInfo");
    i18n_ReportCardInfo =kony.i18n.getLocalizedString("i18n.cards.ReportCardInfo");
    i18n_ReplacementCardInfo =kony.i18n.getLocalizedString("i18n.cards.ReplacementCardInfo");
    i18n_CardHolderC =kony.i18n.getLocalizedString("i18n.cards.CardHolderC");
    i18n_ValidThroughC =kony.i18n.getLocalizedString("i18n.cards.ValidThroughC");
    i18n_Card =kony.i18n.getLocalizedString("i18n.cards.Card");
    i18n_cardNumberxC =kony.i18n.getLocalizedString("i18n.cards.cardNumberxC");
    i18n_CardTypec =kony.i18n.getLocalizedString("i18n.cards.CardTypec"); 
    i18n_selectCountryAlert =kony.i18n.getLocalizedString("i18n.billPay.selectCountryAlert"); 
    i18n_enterBeneficiaryNameAlert =kony.i18n.getLocalizedString("i18n.billPay.enterBeneficiaryNameAlert"); 
    i18n_enterAccountNumberAlert =kony.i18n.getLocalizedString("i18n.billPay.enterAccountNumberAlert"); 
    i18n_enterswiftCodeAlert =kony.i18n.getLocalizedString("i18n.billPay.enterswiftCodeAlert"); 
    i18n_enterRoutingNumberAlert =kony.i18n.getLocalizedString("i18n.billPay.enterRoutingNumberAlert"); 
    i18n_payBill =kony.i18n.getLocalizedString("i18n.transfer.payBill"); 
    i18n_editPayBill =kony.i18n.getLocalizedString("i18n.common.editPayBill"); 
    i18n_outStandingBalance =kony.i18n.getLocalizedString("i18n.common.outStandingBalance");
    i18n_ScheduledBillDetails=kony.i18n.getLocalizedString("i18n.billPay.ScheduledBillDetails");
    i18n_CompletedBillDetails=kony.i18n.getLocalizedString("i18n.billPay.CompletedBillDetails");
    i18n_companyNameAlert=kony.i18n.getLocalizedString("i18n.billPay.companyNameAlert");
    i18n_payeeNickNameAlert=kony.i18n.getLocalizedString("i18n.billPay.payeeNickNameAlert");
    i18n_reenterAccountNumberAlert=kony.i18n.getLocalizedString("i18n.billPay.reenterAccountNumberAlert");
    i18n_enterZipCode=kony.i18n.getLocalizedString("i18n.common.enterZipCode");
    i18n_accountNumberReAccountNumberAlert=kony.i18n.getLocalizedString("i18n.billPay.accountNumberReAccountNumberAlert");
    i18n_currentBalance=kony.i18n.getLocalizedString("i18n.common.currentBalance");
    i18n_billPayEdit=kony.i18n.getLocalizedString("i18n.common.billPayEdit");
	i18n_pay=kony.i18n.getLocalizedString("i18n.transfer.pay");
    i18n_processingTransaction=kony.i18n.getLocalizedString("i18n.success.processingTransaction");
    i18n_successText=kony.i18n.getLocalizedString("i18n.common.successText");
    i18n_payAPerson=kony.i18n.getLocalizedString("i18n.transfer.payAPerson");
	i18n_asOfToday=kony.i18n.getLocalizedString("i18n.overview.asOfToday");
    i18n_PaymentDueDateg=kony.i18n.getLocalizedString("i18n.cards.PaymentDueDateg");
    i18n_maturityDate=kony.i18n.getLocalizedString("i18n.overview.maturityDate");
    i18n_lastStatementBalanceg=kony.i18n.getLocalizedString("i18n.cards.lastStatementBalanceg");
    i18n_cashFlow=kony.i18n.getLocalizedString("i18n.overview.cashFlow");
    i18n_lastMonthC=kony.i18n.getLocalizedString("i18n.charts.lastMonthC");
    i18n_thisMonthC = kony.i18n.getLocalizedString("i18n.charts.thisMonthC");
    i18n_swipeMsg = kony.i18n.getLocalizedString("i18n.swipeMsg");
    i18n_appLaunchError=kony.i18n.getLocalizedString("i18n.errorMsg.appLaunchError");
    i18n_deviceConnectionError = kony.i18n.getLocalizedString("i18n.errorMsg.deviceConnectionError");
    i18n_asOf = kony.i18n.getLocalizedString("i18n.login.asOf");
    i18n_touchIdMsg = kony.i18n.getLocalizedString("i18n.touchIdMsg");
    i18n_alertInvalidCred = kony.i18n.getLocalizedString("i18n.login.alertInvalidCred");
  	i18n_alertAuthCancelUser = kony.i18n.getLocalizedString("i18n.login.alertAuthCancelUser");
  	i18n_alertAuthCancelBackBtn = kony.i18n.getLocalizedString("i18n.login.alertAuthCancelBackBtn");
  	i18n_alertAuthCancelSystem = kony.i18n.getLocalizedString("i18n.login.alertAuthCancelSystem");
  	i18n_alertPasscodeNotSet = kony.i18n.getLocalizedString("i18n.login.alertPasscodeNotSet");
  	i18n_alertTouchIdUnavailable = kony.i18n.getLocalizedString("i18n.login.alertTouchIdUnavailable");
  	i18n_alertTouchIdNotEnrolled = kony.i18n.getLocalizedString("i18n.login.alertTouchIdNotEnrolled");
  	i18n_alertTouchIdAuthFailed = kony.i18n.getLocalizedString("i18n.login.alertTouchIdAuthFailed");
    i18n_dailError=kony.i18n.getLocalizedString("i18n.error.dail");
    i18n_turnOnLocationAlert = kony.i18n.getLocalizedString("i18n.maps.turnOnLocationAlert");
    i18n_DistanceUnknown = kony.i18n.getLocalizedString("i18n.maps.DistanceUnknown");
    i18n_edit = kony.i18n.getLocalizedString("i18n.common.edit");
	i18n_repeatP2P = kony.i18n.getLocalizedString("i18n.transfer.RepeatP2P");
    i18n_depositSuccMsg = kony.i18n.getLocalizedString("i18n.deposits.succesMessage");
    i18n_searchTransactions = kony.i18n.getLocalizedString("i18n.search.SearchTransactions");
    i18n_viewAcntInfo = kony.i18n.getLocalizedString("i18n.commmon.viewAccountInfo"); 
    i18n_viewAcntStatements = kony.i18n.getLocalizedString("i18n.commmon.viewStatements");
    i18n_touchIdalertAndroid =kony.i18n.getLocalizedString("i18n.touchId.disableAdrdTouch");
    i18n_touchIdalertAndroidMsg= kony.i18n.getLocalizedString("i18n.touchId.disableAdrdFingerprint");
    i18n_goodMorning= kony.i18n.getLocalizedString("i18n.accountPreview.goodMorning");
    i18n_goodEvening=kony.i18n.getLocalizedString("i18n.accountPreview.goodEvening");
    i18n_goodAfternoon=kony.i18n.getLocalizedString("i18n.accountPreview.goodAfternoon");
  

}



function geti18nkey(stringValue,noKeyValue)
{
   return  kony.i18n.getLocalizedString(stringValue) ? kony.i18n.getLocalizedString(stringValue):noKeyValue;
}